### ISSUE TITLE
(option to) disable auto restart of Kodi

### ISSUE THREAD

**Issue by idznak** [blunden/XBMCLauncher#5]
when shutting down or closing the kodi-app the xbmc-launcher automatically restarts kodi.
How to disable this feature? 
Because of this it's not possible for me to shutdown my android media player 

My Kodi setup is very stabil, so i don't need the automatic restart option. Is is possible to make the auto restart feature optional?

android media player: orbsmart s92
Kodiversion: 14.0 helix

**Comment by blunden** [comment]
What you are experiencing is essentially that exiting Kodi causes Android to launch your default launcher. Since Kodi is now your launcher, it just launches Kodi again. I'm not sure how easy it would be to detect if the shutdown of Kodi was intentional or not, at least not without irritating false positives.

In the mean time, you can use the Programs menu in Kodi to launch another launcher and turn off your device that way.
