### ISSUE TITLE
Hide Menu bar?

### ISSUE THREAD

**Issue by RobAnt** [blunden/XBMCLauncher#8]
Is it possible to have the launcher hide the menubar before XBMC gets started?  If I hide it after, the full screen doesn;t get used by Kodi.

**Comment by blunden** [comment]
I've never heard of that issue before. XBMC/Kodi is the app that should request that the navigation bar is disabled. I looked into it though and as I thought you need to configure such things on a View. My launcher doesn't use any views since it is meant to just launch XBMC/Kodi as soon as possible.

May I ask what device and Android version you are using?

**Comment by RobAnt** [comment]
It is a TV media player Android 4.4, RK3188T Quad-core.  I've come across the feature request in XBMC/Kodi:
http://forum.kodi.tv/showthread.php?tid=154721
https://github.com/xbmc/xbmc/pull/2091
https://github.com/xbmc/xbmc/pull/3712

but the typical suggestion is to use a 3rd party app like:
https://play.google.com/store/apps/details?id=de.tsorn.FullScreen
https://play.google.com/store/apps/details?id=com.dreamori.hidebar

**Comment by blunden** [comment]
Reading the commits points to the fact that it should successfully hide the navbar on Androdi 4.4 and later.

https://github.com/xbmc/xbmc/commit/d69634359129c300a25812fb04b21bdd3a8202a3

It also works successfully on all the devices I've tried it on. This sounds like a device-specific issue unfortunately and at this time I'm not prepared to severely complicate the app to cater to a few devices that don't implement the Android API properly.

Have you verified that you are running and Kodi build where this change is included?
